# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ed429620354a94a2058a4128c785e1a27246f0391ea7e83a490097c06080f9315c0f285dd303bbf800fc9562a57c27193a0b11a3f931dc892786f369afe53b91

test:
  secret_key_base: 3d954aa1f29ceb1e008e417567af2a20da52fcea48bbd8fa588b5f5d6e2b12d27242ceca8f2a3d74b7d7359edabc6b5f4a89d3d011392d875a3ccd3db76de6bf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
